#+title: Teodor Log

* 2024-04-07
** about 10:00 a teodor log???
Yeah, I'd like a place to dump things when I work.

Under no circumstances do you have to read this file in order to understand things!
** where to start??
Clojure camp thread on Slack:

https://clojurians.slack.com/archives/C0BQDEJ8M/p1711971630025459

Teodor curriculum map draft:

https://play.teod.eu/currmap-clojure-data-science-draft/currmap
** so, where to start?
I propose:

1. We copy the EDN file over
2. We setup a minimal structure to deploy that same page from this repo

Assumptions:

1. We use Cloudflare pages like I did last time
2. We do _not_ build a super-duper flexible build system, we stick to simple things.
** 19:00 I have something working now
status:

we're live on the web,
https://scicloj-garden-experiment.pages.dev/

I've hand-rolled a pandoc to hiccup converter.
Whether that's a good idea remains to be seen.
We can still choose pandoc to convert to html, but then that html is a string, not data.

We're not too far away from an actually useful index to back a curriculum map.
Known missing pieces:

1. An ergonomic way to add new documents
2. An ergonomic way to link between documents
3. Link rewriting (turn uuids into hrefs)

but I think this might work.
We'll see.
